// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewUpdateCustomersParams creates a new UpdateCustomersParams object
// with the default values initialized.
func NewUpdateCustomersParams() *UpdateCustomersParams {
	var ()
	return &UpdateCustomersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCustomersParamsWithTimeout creates a new UpdateCustomersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCustomersParamsWithTimeout(timeout time.Duration) *UpdateCustomersParams {
	var ()
	return &UpdateCustomersParams{

		timeout: timeout,
	}
}

// NewUpdateCustomersParamsWithContext creates a new UpdateCustomersParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCustomersParamsWithContext(ctx context.Context) *UpdateCustomersParams {
	var ()
	return &UpdateCustomersParams{

		Context: ctx,
	}
}

// NewUpdateCustomersParamsWithHTTPClient creates a new UpdateCustomersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCustomersParamsWithHTTPClient(client *http.Client) *UpdateCustomersParams {
	var ()
	return &UpdateCustomersParams{
		HTTPClient: client,
	}
}

/*UpdateCustomersParams contains all the parameters to send to the API endpoint
for the update customers operation typically these are written to a http.Request
*/
type UpdateCustomersParams struct {

	/*Body
	  array of existing customers (id or number required)

	*/
	Body []*models.Customer
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update customers params
func (o *UpdateCustomersParams) WithTimeout(timeout time.Duration) *UpdateCustomersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update customers params
func (o *UpdateCustomersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update customers params
func (o *UpdateCustomersParams) WithContext(ctx context.Context) *UpdateCustomersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update customers params
func (o *UpdateCustomersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update customers params
func (o *UpdateCustomersParams) WithHTTPClient(client *http.Client) *UpdateCustomersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update customers params
func (o *UpdateCustomersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update customers params
func (o *UpdateCustomersParams) WithBody(body []*models.Customer) *UpdateCustomersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update customers params
func (o *UpdateCustomersParams) SetBody(body []*models.Customer) {
	o.Body = body
}

// WithKoronaAccountID adds the koronaAccountID to the update customers params
func (o *UpdateCustomersParams) WithKoronaAccountID(koronaAccountID string) *UpdateCustomersParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the update customers params
func (o *UpdateCustomersParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCustomersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
