// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// DeleteProductsReader is a Reader for the DeleteProducts structure.
type DeleteProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteProductsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteProductsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteProductsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteProductsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteProductsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProductsOK creates a DeleteProductsOK with default headers values
func NewDeleteProductsOK() *DeleteProductsOK {
	return &DeleteProductsOK{}
}

/*DeleteProductsOK handles this case with default header values.

successful operation
*/
type DeleteProductsOK struct {
	Payload []*models.AddOrUpdateResult
}

func (o *DeleteProductsOK) Error() string {
	return fmt.Sprintf("[DELETE /accounts/{koronaAccountId}/products][%d] deleteProductsOK  %+v", 200, o.Payload)
}

func (o *DeleteProductsOK) GetPayload() []*models.AddOrUpdateResult {
	return o.Payload
}

func (o *DeleteProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsBadRequest creates a DeleteProductsBadRequest with default headers values
func NewDeleteProductsBadRequest() *DeleteProductsBadRequest {
	return &DeleteProductsBadRequest{}
}

/*DeleteProductsBadRequest handles this case with default header values.

Malformed querystring or model
*/
type DeleteProductsBadRequest struct {
	Payload *models.BadRequestError
}

func (o *DeleteProductsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /accounts/{koronaAccountId}/products][%d] deleteProductsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteProductsBadRequest) GetPayload() *models.BadRequestError {
	return o.Payload
}

func (o *DeleteProductsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsUnauthorized creates a DeleteProductsUnauthorized with default headers values
func NewDeleteProductsUnauthorized() *DeleteProductsUnauthorized {
	return &DeleteProductsUnauthorized{}
}

/*DeleteProductsUnauthorized handles this case with default header values.

Missing or invalid http-authentication
*/
type DeleteProductsUnauthorized struct {
}

func (o *DeleteProductsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /accounts/{koronaAccountId}/products][%d] deleteProductsUnauthorized ", 401)
}

func (o *DeleteProductsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProductsForbidden creates a DeleteProductsForbidden with default headers values
func NewDeleteProductsForbidden() *DeleteProductsForbidden {
	return &DeleteProductsForbidden{}
}

/*DeleteProductsForbidden handles this case with default header values.

Requested action is not allowed
*/
type DeleteProductsForbidden struct {
	Payload *models.ForbiddenError
}

func (o *DeleteProductsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /accounts/{koronaAccountId}/products][%d] deleteProductsForbidden  %+v", 403, o.Payload)
}

func (o *DeleteProductsForbidden) GetPayload() *models.ForbiddenError {
	return o.Payload
}

func (o *DeleteProductsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ForbiddenError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsNotFound creates a DeleteProductsNotFound with default headers values
func NewDeleteProductsNotFound() *DeleteProductsNotFound {
	return &DeleteProductsNotFound{}
}

/*DeleteProductsNotFound handles this case with default header values.

Object not found
*/
type DeleteProductsNotFound struct {
	Payload *models.NotFoundError
}

func (o *DeleteProductsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /accounts/{koronaAccountId}/products][%d] deleteProductsNotFound  %+v", 404, o.Payload)
}

func (o *DeleteProductsNotFound) GetPayload() *models.NotFoundError {
	return o.Payload
}

func (o *DeleteProductsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsTooManyRequests creates a DeleteProductsTooManyRequests with default headers values
func NewDeleteProductsTooManyRequests() *DeleteProductsTooManyRequests {
	return &DeleteProductsTooManyRequests{}
}

/*DeleteProductsTooManyRequests handles this case with default header values.

Too many requests in a specified period
*/
type DeleteProductsTooManyRequests struct {
	Payload *models.TooManyRequestsError
}

func (o *DeleteProductsTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /accounts/{koronaAccountId}/products][%d] deleteProductsTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeleteProductsTooManyRequests) GetPayload() *models.TooManyRequestsError {
	return o.Payload
}

func (o *DeleteProductsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TooManyRequestsError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
