// Code generated by go-swagger; DO NOT EDIT.

package economic_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEconomicZoneParams creates a new GetEconomicZoneParams object
// with the default values initialized.
func NewGetEconomicZoneParams() *GetEconomicZoneParams {
	var ()
	return &GetEconomicZoneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEconomicZoneParamsWithTimeout creates a new GetEconomicZoneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEconomicZoneParamsWithTimeout(timeout time.Duration) *GetEconomicZoneParams {
	var ()
	return &GetEconomicZoneParams{

		timeout: timeout,
	}
}

// NewGetEconomicZoneParamsWithContext creates a new GetEconomicZoneParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEconomicZoneParamsWithContext(ctx context.Context) *GetEconomicZoneParams {
	var ()
	return &GetEconomicZoneParams{

		Context: ctx,
	}
}

// NewGetEconomicZoneParamsWithHTTPClient creates a new GetEconomicZoneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEconomicZoneParamsWithHTTPClient(client *http.Client) *GetEconomicZoneParams {
	var ()
	return &GetEconomicZoneParams{
		HTTPClient: client,
	}
}

/*GetEconomicZoneParams contains all the parameters to send to the API endpoint
for the get economic zone operation typically these are written to a http.Request
*/
type GetEconomicZoneParams struct {

	/*EconomicZoneID
	  id of the related object (important: id should match the uuid-format)

	*/
	EconomicZoneID string
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get economic zone params
func (o *GetEconomicZoneParams) WithTimeout(timeout time.Duration) *GetEconomicZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get economic zone params
func (o *GetEconomicZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get economic zone params
func (o *GetEconomicZoneParams) WithContext(ctx context.Context) *GetEconomicZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get economic zone params
func (o *GetEconomicZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get economic zone params
func (o *GetEconomicZoneParams) WithHTTPClient(client *http.Client) *GetEconomicZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get economic zone params
func (o *GetEconomicZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEconomicZoneID adds the economicZoneID to the get economic zone params
func (o *GetEconomicZoneParams) WithEconomicZoneID(economicZoneID string) *GetEconomicZoneParams {
	o.SetEconomicZoneID(economicZoneID)
	return o
}

// SetEconomicZoneID adds the economicZoneId to the get economic zone params
func (o *GetEconomicZoneParams) SetEconomicZoneID(economicZoneID string) {
	o.EconomicZoneID = economicZoneID
}

// WithKoronaAccountID adds the koronaAccountID to the get economic zone params
func (o *GetEconomicZoneParams) WithKoronaAccountID(koronaAccountID string) *GetEconomicZoneParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the get economic zone params
func (o *GetEconomicZoneParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEconomicZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param economicZoneId
	if err := r.SetPathParam("economicZoneId", o.EconomicZoneID); err != nil {
		return err
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
