// Code generated by go-swagger; DO NOT EDIT.

package customer_orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewAddCustomerOrdersParams creates a new AddCustomerOrdersParams object
// with the default values initialized.
func NewAddCustomerOrdersParams() *AddCustomerOrdersParams {
	var ()
	return &AddCustomerOrdersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddCustomerOrdersParamsWithTimeout creates a new AddCustomerOrdersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddCustomerOrdersParamsWithTimeout(timeout time.Duration) *AddCustomerOrdersParams {
	var ()
	return &AddCustomerOrdersParams{

		timeout: timeout,
	}
}

// NewAddCustomerOrdersParamsWithContext creates a new AddCustomerOrdersParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddCustomerOrdersParamsWithContext(ctx context.Context) *AddCustomerOrdersParams {
	var ()
	return &AddCustomerOrdersParams{

		Context: ctx,
	}
}

// NewAddCustomerOrdersParamsWithHTTPClient creates a new AddCustomerOrdersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddCustomerOrdersParamsWithHTTPClient(client *http.Client) *AddCustomerOrdersParams {
	var ()
	return &AddCustomerOrdersParams{
		HTTPClient: client,
	}
}

/*AddCustomerOrdersParams contains all the parameters to send to the API endpoint
for the add customer orders operation typically these are written to a http.Request
*/
type AddCustomerOrdersParams struct {

	/*Body
	  array of new customer orders

	*/
	Body []*models.CustomerOrder
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add customer orders params
func (o *AddCustomerOrdersParams) WithTimeout(timeout time.Duration) *AddCustomerOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add customer orders params
func (o *AddCustomerOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add customer orders params
func (o *AddCustomerOrdersParams) WithContext(ctx context.Context) *AddCustomerOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add customer orders params
func (o *AddCustomerOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add customer orders params
func (o *AddCustomerOrdersParams) WithHTTPClient(client *http.Client) *AddCustomerOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add customer orders params
func (o *AddCustomerOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add customer orders params
func (o *AddCustomerOrdersParams) WithBody(body []*models.CustomerOrder) *AddCustomerOrdersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add customer orders params
func (o *AddCustomerOrdersParams) SetBody(body []*models.CustomerOrder) {
	o.Body = body
}

// WithKoronaAccountID adds the koronaAccountID to the add customer orders params
func (o *AddCustomerOrdersParams) WithKoronaAccountID(koronaAccountID string) *AddCustomerOrdersParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the add customer orders params
func (o *AddCustomerOrdersParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *AddCustomerOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
