// Code generated by go-swagger; DO NOT EDIT.

package organizational_units

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewAddOrganizationalUnitDayRatingsParams creates a new AddOrganizationalUnitDayRatingsParams object
// with the default values initialized.
func NewAddOrganizationalUnitDayRatingsParams() *AddOrganizationalUnitDayRatingsParams {
	var ()
	return &AddOrganizationalUnitDayRatingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddOrganizationalUnitDayRatingsParamsWithTimeout creates a new AddOrganizationalUnitDayRatingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddOrganizationalUnitDayRatingsParamsWithTimeout(timeout time.Duration) *AddOrganizationalUnitDayRatingsParams {
	var ()
	return &AddOrganizationalUnitDayRatingsParams{

		timeout: timeout,
	}
}

// NewAddOrganizationalUnitDayRatingsParamsWithContext creates a new AddOrganizationalUnitDayRatingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddOrganizationalUnitDayRatingsParamsWithContext(ctx context.Context) *AddOrganizationalUnitDayRatingsParams {
	var ()
	return &AddOrganizationalUnitDayRatingsParams{

		Context: ctx,
	}
}

// NewAddOrganizationalUnitDayRatingsParamsWithHTTPClient creates a new AddOrganizationalUnitDayRatingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddOrganizationalUnitDayRatingsParamsWithHTTPClient(client *http.Client) *AddOrganizationalUnitDayRatingsParams {
	var ()
	return &AddOrganizationalUnitDayRatingsParams{
		HTTPClient: client,
	}
}

/*AddOrganizationalUnitDayRatingsParams contains all the parameters to send to the API endpoint
for the add organizational unit day ratings operation typically these are written to a http.Request
*/
type AddOrganizationalUnitDayRatingsParams struct {

	/*Body
	  an array of new day ratings

	*/
	Body []*models.DayRating
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string
	/*OrganizationalUnitID
	  id of the related object (important: id should match the uuid-format)

	*/
	OrganizationalUnitID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) WithTimeout(timeout time.Duration) *AddOrganizationalUnitDayRatingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) WithContext(ctx context.Context) *AddOrganizationalUnitDayRatingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) WithHTTPClient(client *http.Client) *AddOrganizationalUnitDayRatingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) WithBody(body []*models.DayRating) *AddOrganizationalUnitDayRatingsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) SetBody(body []*models.DayRating) {
	o.Body = body
}

// WithKoronaAccountID adds the koronaAccountID to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) WithKoronaAccountID(koronaAccountID string) *AddOrganizationalUnitDayRatingsParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WithOrganizationalUnitID adds the organizationalUnitID to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) WithOrganizationalUnitID(organizationalUnitID string) *AddOrganizationalUnitDayRatingsParams {
	o.SetOrganizationalUnitID(organizationalUnitID)
	return o
}

// SetOrganizationalUnitID adds the organizationalUnitId to the add organizational unit day ratings params
func (o *AddOrganizationalUnitDayRatingsParams) SetOrganizationalUnitID(organizationalUnitID string) {
	o.OrganizationalUnitID = organizationalUnitID
}

// WriteToRequest writes these params to a swagger request
func (o *AddOrganizationalUnitDayRatingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	// path param organizationalUnitId
	if err := r.SetPathParam("organizationalUnitId", o.OrganizationalUnitID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
