// Code generated by go-swagger; DO NOT EDIT.

package organizational_units

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationalUnitDayRatingParams creates a new DeleteOrganizationalUnitDayRatingParams object
// with the default values initialized.
func NewDeleteOrganizationalUnitDayRatingParams() *DeleteOrganizationalUnitDayRatingParams {
	var ()
	return &DeleteOrganizationalUnitDayRatingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationalUnitDayRatingParamsWithTimeout creates a new DeleteOrganizationalUnitDayRatingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrganizationalUnitDayRatingParamsWithTimeout(timeout time.Duration) *DeleteOrganizationalUnitDayRatingParams {
	var ()
	return &DeleteOrganizationalUnitDayRatingParams{

		timeout: timeout,
	}
}

// NewDeleteOrganizationalUnitDayRatingParamsWithContext creates a new DeleteOrganizationalUnitDayRatingParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrganizationalUnitDayRatingParamsWithContext(ctx context.Context) *DeleteOrganizationalUnitDayRatingParams {
	var ()
	return &DeleteOrganizationalUnitDayRatingParams{

		Context: ctx,
	}
}

// NewDeleteOrganizationalUnitDayRatingParamsWithHTTPClient creates a new DeleteOrganizationalUnitDayRatingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrganizationalUnitDayRatingParamsWithHTTPClient(client *http.Client) *DeleteOrganizationalUnitDayRatingParams {
	var ()
	return &DeleteOrganizationalUnitDayRatingParams{
		HTTPClient: client,
	}
}

/*DeleteOrganizationalUnitDayRatingParams contains all the parameters to send to the API endpoint
for the delete organizational unit day rating operation typically these are written to a http.Request
*/
type DeleteOrganizationalUnitDayRatingParams struct {

	/*DayRatingIDOrDate
	  the id or date (YYYY-MM-DD) of the day rating

	*/
	DayRatingIDOrDate string
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string
	/*OrganizationalUnitID
	  id of the related object (important: id should match the uuid-format)

	*/
	OrganizationalUnitID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) WithTimeout(timeout time.Duration) *DeleteOrganizationalUnitDayRatingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) WithContext(ctx context.Context) *DeleteOrganizationalUnitDayRatingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) WithHTTPClient(client *http.Client) *DeleteOrganizationalUnitDayRatingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDayRatingIDOrDate adds the dayRatingIDOrDate to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) WithDayRatingIDOrDate(dayRatingIDOrDate string) *DeleteOrganizationalUnitDayRatingParams {
	o.SetDayRatingIDOrDate(dayRatingIDOrDate)
	return o
}

// SetDayRatingIDOrDate adds the dayRatingIdOrDate to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) SetDayRatingIDOrDate(dayRatingIDOrDate string) {
	o.DayRatingIDOrDate = dayRatingIDOrDate
}

// WithKoronaAccountID adds the koronaAccountID to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) WithKoronaAccountID(koronaAccountID string) *DeleteOrganizationalUnitDayRatingParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WithOrganizationalUnitID adds the organizationalUnitID to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) WithOrganizationalUnitID(organizationalUnitID string) *DeleteOrganizationalUnitDayRatingParams {
	o.SetOrganizationalUnitID(organizationalUnitID)
	return o
}

// SetOrganizationalUnitID adds the organizationalUnitId to the delete organizational unit day rating params
func (o *DeleteOrganizationalUnitDayRatingParams) SetOrganizationalUnitID(organizationalUnitID string) {
	o.OrganizationalUnitID = organizationalUnitID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationalUnitDayRatingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dayRatingIdOrDate
	if err := r.SetPathParam("dayRatingIdOrDate", o.DayRatingIDOrDate); err != nil {
		return err
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	// path param organizationalUnitId
	if err := r.SetPathParam("organizationalUnitId", o.OrganizationalUnitID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
