// Code generated by go-swagger; DO NOT EDIT.

package organizational_units

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationalUnitDayRatingsParams creates a new GetOrganizationalUnitDayRatingsParams object
// with the default values initialized.
func NewGetOrganizationalUnitDayRatingsParams() *GetOrganizationalUnitDayRatingsParams {
	var ()
	return &GetOrganizationalUnitDayRatingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationalUnitDayRatingsParamsWithTimeout creates a new GetOrganizationalUnitDayRatingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationalUnitDayRatingsParamsWithTimeout(timeout time.Duration) *GetOrganizationalUnitDayRatingsParams {
	var ()
	return &GetOrganizationalUnitDayRatingsParams{

		timeout: timeout,
	}
}

// NewGetOrganizationalUnitDayRatingsParamsWithContext creates a new GetOrganizationalUnitDayRatingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationalUnitDayRatingsParamsWithContext(ctx context.Context) *GetOrganizationalUnitDayRatingsParams {
	var ()
	return &GetOrganizationalUnitDayRatingsParams{

		Context: ctx,
	}
}

// NewGetOrganizationalUnitDayRatingsParamsWithHTTPClient creates a new GetOrganizationalUnitDayRatingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationalUnitDayRatingsParamsWithHTTPClient(client *http.Client) *GetOrganizationalUnitDayRatingsParams {
	var ()
	return &GetOrganizationalUnitDayRatingsParams{
		HTTPClient: client,
	}
}

/*GetOrganizationalUnitDayRatingsParams contains all the parameters to send to the API endpoint
for the get organizational unit day ratings operation typically these are written to a http.Request
*/
type GetOrganizationalUnitDayRatingsParams struct {

	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string
	/*OrganizationalUnitID
	  id of the related object (important: id should match the uuid-format)

	*/
	OrganizationalUnitID string
	/*Page
	  number of the page to fetch

	*/
	Page *int32
	/*Size
	  amount of objects to return per page

	*/
	Size *int32
	/*Sort
	  attribute to sort by (multiple separated by comma; max. 5)

	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithTimeout(timeout time.Duration) *GetOrganizationalUnitDayRatingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithContext(ctx context.Context) *GetOrganizationalUnitDayRatingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithHTTPClient(client *http.Client) *GetOrganizationalUnitDayRatingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKoronaAccountID adds the koronaAccountID to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithKoronaAccountID(koronaAccountID string) *GetOrganizationalUnitDayRatingsParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WithOrganizationalUnitID adds the organizationalUnitID to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithOrganizationalUnitID(organizationalUnitID string) *GetOrganizationalUnitDayRatingsParams {
	o.SetOrganizationalUnitID(organizationalUnitID)
	return o
}

// SetOrganizationalUnitID adds the organizationalUnitId to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetOrganizationalUnitID(organizationalUnitID string) {
	o.OrganizationalUnitID = organizationalUnitID
}

// WithPage adds the page to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithPage(page *int32) *GetOrganizationalUnitDayRatingsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetPage(page *int32) {
	o.Page = page
}

// WithSize adds the size to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithSize(size *int32) *GetOrganizationalUnitDayRatingsParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetSize(size *int32) {
	o.Size = size
}

// WithSort adds the sort to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) WithSort(sort *string) *GetOrganizationalUnitDayRatingsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get organizational unit day ratings params
func (o *GetOrganizationalUnitDayRatingsParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationalUnitDayRatingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	// path param organizationalUnitId
	if err := r.SetPathParam("organizationalUnitId", o.OrganizationalUnitID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.Size != nil {

		// query param size
		var qrSize int32
		if o.Size != nil {
			qrSize = *o.Size
		}
		qSize := swag.FormatInt32(qrSize)
		if qSize != "" {
			if err := r.SetQueryParam("size", qSize); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
