// Code generated by go-swagger; DO NOT EDIT.

package cashiers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new cashiers API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for cashiers API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetCashier(params *GetCashierParams, authInfo runtime.ClientAuthInfoWriter) (*GetCashierOK, error)

	GetCashiers(params *GetCashiersParams, authInfo runtime.ClientAuthInfoWriter) (*GetCashiersOK, *GetCashiersNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetCashier returns the single cashier
*/
func (a *Client) GetCashier(params *GetCashierParams, authInfo runtime.ClientAuthInfoWriter) (*GetCashierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCashierParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCashier",
		Method:             "GET",
		PathPattern:        "/accounts/{koronaAccountId}/cashiers/{cashierId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCashierReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCashierOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCashier: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCashiers lists all cashiers
*/
func (a *Client) GetCashiers(params *GetCashiersParams, authInfo runtime.ClientAuthInfoWriter) (*GetCashiersOK, *GetCashiersNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCashiersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCashiers",
		Method:             "GET",
		PathPattern:        "/accounts/{koronaAccountId}/cashiers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCashiersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *GetCashiersOK:
		return value, nil, nil
	case *GetCashiersNoContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for cashiers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
