// Code generated by go-swagger; DO NOT EDIT.

package statistics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// GetTopSellerReader is a Reader for the GetTopSeller structure.
type GetTopSellerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTopSellerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTopSellerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTopSellerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetTopSellerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetTopSellerForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetTopSellerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetTopSellerTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTopSellerOK creates a GetTopSellerOK with default headers values
func NewGetTopSellerOK() *GetTopSellerOK {
	return &GetTopSellerOK{}
}

/*GetTopSellerOK handles this case with default header values.

successful operation
*/
type GetTopSellerOK struct {
	Payload *models.StatisticListTopSeller
}

func (o *GetTopSellerOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{koronaAccountId}/statistics/topSeller][%d] getTopSellerOK  %+v", 200, o.Payload)
}

func (o *GetTopSellerOK) GetPayload() *models.StatisticListTopSeller {
	return o.Payload
}

func (o *GetTopSellerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatisticListTopSeller)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTopSellerBadRequest creates a GetTopSellerBadRequest with default headers values
func NewGetTopSellerBadRequest() *GetTopSellerBadRequest {
	return &GetTopSellerBadRequest{}
}

/*GetTopSellerBadRequest handles this case with default header values.

Malformed querystring or model
*/
type GetTopSellerBadRequest struct {
	Payload *models.BadRequestError
}

func (o *GetTopSellerBadRequest) Error() string {
	return fmt.Sprintf("[GET /accounts/{koronaAccountId}/statistics/topSeller][%d] getTopSellerBadRequest  %+v", 400, o.Payload)
}

func (o *GetTopSellerBadRequest) GetPayload() *models.BadRequestError {
	return o.Payload
}

func (o *GetTopSellerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTopSellerUnauthorized creates a GetTopSellerUnauthorized with default headers values
func NewGetTopSellerUnauthorized() *GetTopSellerUnauthorized {
	return &GetTopSellerUnauthorized{}
}

/*GetTopSellerUnauthorized handles this case with default header values.

Missing or invalid http-authentication
*/
type GetTopSellerUnauthorized struct {
}

func (o *GetTopSellerUnauthorized) Error() string {
	return fmt.Sprintf("[GET /accounts/{koronaAccountId}/statistics/topSeller][%d] getTopSellerUnauthorized ", 401)
}

func (o *GetTopSellerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTopSellerForbidden creates a GetTopSellerForbidden with default headers values
func NewGetTopSellerForbidden() *GetTopSellerForbidden {
	return &GetTopSellerForbidden{}
}

/*GetTopSellerForbidden handles this case with default header values.

Requested action is not allowed
*/
type GetTopSellerForbidden struct {
	Payload *models.ForbiddenError
}

func (o *GetTopSellerForbidden) Error() string {
	return fmt.Sprintf("[GET /accounts/{koronaAccountId}/statistics/topSeller][%d] getTopSellerForbidden  %+v", 403, o.Payload)
}

func (o *GetTopSellerForbidden) GetPayload() *models.ForbiddenError {
	return o.Payload
}

func (o *GetTopSellerForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ForbiddenError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTopSellerNotFound creates a GetTopSellerNotFound with default headers values
func NewGetTopSellerNotFound() *GetTopSellerNotFound {
	return &GetTopSellerNotFound{}
}

/*GetTopSellerNotFound handles this case with default header values.

Object not found
*/
type GetTopSellerNotFound struct {
	Payload *models.NotFoundError
}

func (o *GetTopSellerNotFound) Error() string {
	return fmt.Sprintf("[GET /accounts/{koronaAccountId}/statistics/topSeller][%d] getTopSellerNotFound  %+v", 404, o.Payload)
}

func (o *GetTopSellerNotFound) GetPayload() *models.NotFoundError {
	return o.Payload
}

func (o *GetTopSellerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTopSellerTooManyRequests creates a GetTopSellerTooManyRequests with default headers values
func NewGetTopSellerTooManyRequests() *GetTopSellerTooManyRequests {
	return &GetTopSellerTooManyRequests{}
}

/*GetTopSellerTooManyRequests handles this case with default header values.

Too many requests in a specified period
*/
type GetTopSellerTooManyRequests struct {
	Payload *models.TooManyRequestsError
}

func (o *GetTopSellerTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /accounts/{koronaAccountId}/statistics/topSeller][%d] getTopSellerTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetTopSellerTooManyRequests) GetPayload() *models.TooManyRequestsError {
	return o.Payload
}

func (o *GetTopSellerTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TooManyRequestsError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
