// Code generated by go-swagger; DO NOT EDIT.

package statistics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRevenueForCustomerGroupsParams creates a new GetRevenueForCustomerGroupsParams object
// with the default values initialized.
func NewGetRevenueForCustomerGroupsParams() *GetRevenueForCustomerGroupsParams {
	var ()
	return &GetRevenueForCustomerGroupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRevenueForCustomerGroupsParamsWithTimeout creates a new GetRevenueForCustomerGroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRevenueForCustomerGroupsParamsWithTimeout(timeout time.Duration) *GetRevenueForCustomerGroupsParams {
	var ()
	return &GetRevenueForCustomerGroupsParams{

		timeout: timeout,
	}
}

// NewGetRevenueForCustomerGroupsParamsWithContext creates a new GetRevenueForCustomerGroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRevenueForCustomerGroupsParamsWithContext(ctx context.Context) *GetRevenueForCustomerGroupsParams {
	var ()
	return &GetRevenueForCustomerGroupsParams{

		Context: ctx,
	}
}

// NewGetRevenueForCustomerGroupsParamsWithHTTPClient creates a new GetRevenueForCustomerGroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRevenueForCustomerGroupsParamsWithHTTPClient(client *http.Client) *GetRevenueForCustomerGroupsParams {
	var ()
	return &GetRevenueForCustomerGroupsParams{
		HTTPClient: client,
	}
}

/*GetRevenueForCustomerGroupsParams contains all the parameters to send to the API endpoint
for the get revenue for customer groups operation typically these are written to a http.Request
*/
type GetRevenueForCustomerGroupsParams struct {

	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string
	/*OrganizationalUnit
	  number of the organizational unit

	*/
	OrganizationalUnit *string
	/*Period
	  time period for comparison

	*/
	Period *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) WithTimeout(timeout time.Duration) *GetRevenueForCustomerGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) WithContext(ctx context.Context) *GetRevenueForCustomerGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) WithHTTPClient(client *http.Client) *GetRevenueForCustomerGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKoronaAccountID adds the koronaAccountID to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) WithKoronaAccountID(koronaAccountID string) *GetRevenueForCustomerGroupsParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WithOrganizationalUnit adds the organizationalUnit to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) WithOrganizationalUnit(organizationalUnit *string) *GetRevenueForCustomerGroupsParams {
	o.SetOrganizationalUnit(organizationalUnit)
	return o
}

// SetOrganizationalUnit adds the organizationalUnit to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) SetOrganizationalUnit(organizationalUnit *string) {
	o.OrganizationalUnit = organizationalUnit
}

// WithPeriod adds the period to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) WithPeriod(period *string) *GetRevenueForCustomerGroupsParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get revenue for customer groups params
func (o *GetRevenueForCustomerGroupsParams) SetPeriod(period *string) {
	o.Period = period
}

// WriteToRequest writes these params to a swagger request
func (o *GetRevenueForCustomerGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if o.OrganizationalUnit != nil {

		// query param organizationalUnit
		var qrOrganizationalUnit string
		if o.OrganizationalUnit != nil {
			qrOrganizationalUnit = *o.OrganizationalUnit
		}
		qOrganizationalUnit := qrOrganizationalUnit
		if qOrganizationalUnit != "" {
			if err := r.SetQueryParam("organizationalUnit", qOrganizationalUnit); err != nil {
				return err
			}
		}

	}

	if o.Period != nil {

		// query param period
		var qrPeriod string
		if o.Period != nil {
			qrPeriod = *o.Period
		}
		qPeriod := qrPeriod
		if qPeriod != "" {
			if err := r.SetQueryParam("period", qPeriod); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
