// Code generated by go-swagger; DO NOT EDIT.

package stock_receipts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewAddStockReceiptsParams creates a new AddStockReceiptsParams object
// with the default values initialized.
func NewAddStockReceiptsParams() *AddStockReceiptsParams {
	var ()
	return &AddStockReceiptsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddStockReceiptsParamsWithTimeout creates a new AddStockReceiptsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddStockReceiptsParamsWithTimeout(timeout time.Duration) *AddStockReceiptsParams {
	var ()
	return &AddStockReceiptsParams{

		timeout: timeout,
	}
}

// NewAddStockReceiptsParamsWithContext creates a new AddStockReceiptsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddStockReceiptsParamsWithContext(ctx context.Context) *AddStockReceiptsParams {
	var ()
	return &AddStockReceiptsParams{

		Context: ctx,
	}
}

// NewAddStockReceiptsParamsWithHTTPClient creates a new AddStockReceiptsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddStockReceiptsParamsWithHTTPClient(client *http.Client) *AddStockReceiptsParams {
	var ()
	return &AddStockReceiptsParams{
		HTTPClient: client,
	}
}

/*AddStockReceiptsParams contains all the parameters to send to the API endpoint
for the add stock receipts operation typically these are written to a http.Request
*/
type AddStockReceiptsParams struct {

	/*Body
	  data to add

	*/
	Body []*models.StockReceipt
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add stock receipts params
func (o *AddStockReceiptsParams) WithTimeout(timeout time.Duration) *AddStockReceiptsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add stock receipts params
func (o *AddStockReceiptsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add stock receipts params
func (o *AddStockReceiptsParams) WithContext(ctx context.Context) *AddStockReceiptsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add stock receipts params
func (o *AddStockReceiptsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add stock receipts params
func (o *AddStockReceiptsParams) WithHTTPClient(client *http.Client) *AddStockReceiptsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add stock receipts params
func (o *AddStockReceiptsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add stock receipts params
func (o *AddStockReceiptsParams) WithBody(body []*models.StockReceipt) *AddStockReceiptsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add stock receipts params
func (o *AddStockReceiptsParams) SetBody(body []*models.StockReceipt) {
	o.Body = body
}

// WithKoronaAccountID adds the koronaAccountID to the add stock receipts params
func (o *AddStockReceiptsParams) WithKoronaAccountID(koronaAccountID string) *AddStockReceiptsParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the add stock receipts params
func (o *AddStockReceiptsParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *AddStockReceiptsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
