// Code generated by go-swagger; DO NOT EDIT.

package stock_receipts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetStockReceiptItemsParams creates a new GetStockReceiptItemsParams object
// with the default values initialized.
func NewGetStockReceiptItemsParams() *GetStockReceiptItemsParams {
	var ()
	return &GetStockReceiptItemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStockReceiptItemsParamsWithTimeout creates a new GetStockReceiptItemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStockReceiptItemsParamsWithTimeout(timeout time.Duration) *GetStockReceiptItemsParams {
	var ()
	return &GetStockReceiptItemsParams{

		timeout: timeout,
	}
}

// NewGetStockReceiptItemsParamsWithContext creates a new GetStockReceiptItemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStockReceiptItemsParamsWithContext(ctx context.Context) *GetStockReceiptItemsParams {
	var ()
	return &GetStockReceiptItemsParams{

		Context: ctx,
	}
}

// NewGetStockReceiptItemsParamsWithHTTPClient creates a new GetStockReceiptItemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStockReceiptItemsParamsWithHTTPClient(client *http.Client) *GetStockReceiptItemsParams {
	var ()
	return &GetStockReceiptItemsParams{
		HTTPClient: client,
	}
}

/*GetStockReceiptItemsParams contains all the parameters to send to the API endpoint
for the get stock receipt items operation typically these are written to a http.Request
*/
type GetStockReceiptItemsParams struct {

	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string
	/*Page
	  number of the page to fetch

	*/
	Page *int32
	/*Revision
	  last revision number, objects with a greater revision than this will be returned

	*/
	Revision *int64
	/*Size
	  amount of objects to return per page

	*/
	Size *int32
	/*Sort
	  attribute to sort by (multiple separated by comma; max. 5)

	*/
	Sort *string
	/*StockReceiptID
	  id of the related object (important: id should match the uuid-format)

	*/
	StockReceiptID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithTimeout(timeout time.Duration) *GetStockReceiptItemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithContext(ctx context.Context) *GetStockReceiptItemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithHTTPClient(client *http.Client) *GetStockReceiptItemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKoronaAccountID adds the koronaAccountID to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithKoronaAccountID(koronaAccountID string) *GetStockReceiptItemsParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WithPage adds the page to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithPage(page *int32) *GetStockReceiptItemsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetPage(page *int32) {
	o.Page = page
}

// WithRevision adds the revision to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithRevision(revision *int64) *GetStockReceiptItemsParams {
	o.SetRevision(revision)
	return o
}

// SetRevision adds the revision to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetRevision(revision *int64) {
	o.Revision = revision
}

// WithSize adds the size to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithSize(size *int32) *GetStockReceiptItemsParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetSize(size *int32) {
	o.Size = size
}

// WithSort adds the sort to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithSort(sort *string) *GetStockReceiptItemsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithStockReceiptID adds the stockReceiptID to the get stock receipt items params
func (o *GetStockReceiptItemsParams) WithStockReceiptID(stockReceiptID string) *GetStockReceiptItemsParams {
	o.SetStockReceiptID(stockReceiptID)
	return o
}

// SetStockReceiptID adds the stockReceiptId to the get stock receipt items params
func (o *GetStockReceiptItemsParams) SetStockReceiptID(stockReceiptID string) {
	o.StockReceiptID = stockReceiptID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStockReceiptItemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.Revision != nil {

		// query param revision
		var qrRevision int64
		if o.Revision != nil {
			qrRevision = *o.Revision
		}
		qRevision := swag.FormatInt64(qrRevision)
		if qRevision != "" {
			if err := r.SetQueryParam("revision", qRevision); err != nil {
				return err
			}
		}

	}

	if o.Size != nil {

		// query param size
		var qrSize int32
		if o.Size != nil {
			qrSize = *o.Size
		}
		qSize := swag.FormatInt32(qrSize)
		if qSize != "" {
			if err := r.SetQueryParam("size", qSize); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	// path param stockReceiptId
	if err := r.SetPathParam("stockReceiptId", o.StockReceiptID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
