// Code generated by go-swagger; DO NOT EDIT.

package payment_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPaymentMethodParams creates a new GetPaymentMethodParams object
// with the default values initialized.
func NewGetPaymentMethodParams() *GetPaymentMethodParams {
	var ()
	return &GetPaymentMethodParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPaymentMethodParamsWithTimeout creates a new GetPaymentMethodParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPaymentMethodParamsWithTimeout(timeout time.Duration) *GetPaymentMethodParams {
	var ()
	return &GetPaymentMethodParams{

		timeout: timeout,
	}
}

// NewGetPaymentMethodParamsWithContext creates a new GetPaymentMethodParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPaymentMethodParamsWithContext(ctx context.Context) *GetPaymentMethodParams {
	var ()
	return &GetPaymentMethodParams{

		Context: ctx,
	}
}

// NewGetPaymentMethodParamsWithHTTPClient creates a new GetPaymentMethodParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPaymentMethodParamsWithHTTPClient(client *http.Client) *GetPaymentMethodParams {
	var ()
	return &GetPaymentMethodParams{
		HTTPClient: client,
	}
}

/*GetPaymentMethodParams contains all the parameters to send to the API endpoint
for the get payment method operation typically these are written to a http.Request
*/
type GetPaymentMethodParams struct {

	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string
	/*PaymentMethodID
	  id of the related object (important: id should match the uuid-format)

	*/
	PaymentMethodID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get payment method params
func (o *GetPaymentMethodParams) WithTimeout(timeout time.Duration) *GetPaymentMethodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get payment method params
func (o *GetPaymentMethodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get payment method params
func (o *GetPaymentMethodParams) WithContext(ctx context.Context) *GetPaymentMethodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get payment method params
func (o *GetPaymentMethodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get payment method params
func (o *GetPaymentMethodParams) WithHTTPClient(client *http.Client) *GetPaymentMethodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get payment method params
func (o *GetPaymentMethodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKoronaAccountID adds the koronaAccountID to the get payment method params
func (o *GetPaymentMethodParams) WithKoronaAccountID(koronaAccountID string) *GetPaymentMethodParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the get payment method params
func (o *GetPaymentMethodParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WithPaymentMethodID adds the paymentMethodID to the get payment method params
func (o *GetPaymentMethodParams) WithPaymentMethodID(paymentMethodID string) *GetPaymentMethodParams {
	o.SetPaymentMethodID(paymentMethodID)
	return o
}

// SetPaymentMethodID adds the paymentMethodId to the get payment method params
func (o *GetPaymentMethodParams) SetPaymentMethodID(paymentMethodID string) {
	o.PaymentMethodID = paymentMethodID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPaymentMethodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	// path param paymentMethodId
	if err := r.SetPathParam("paymentMethodId", o.PaymentMethodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
