// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewAddInventoriesParams creates a new AddInventoriesParams object
// with the default values initialized.
func NewAddInventoriesParams() *AddInventoriesParams {
	var ()
	return &AddInventoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddInventoriesParamsWithTimeout creates a new AddInventoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddInventoriesParamsWithTimeout(timeout time.Duration) *AddInventoriesParams {
	var ()
	return &AddInventoriesParams{

		timeout: timeout,
	}
}

// NewAddInventoriesParamsWithContext creates a new AddInventoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddInventoriesParamsWithContext(ctx context.Context) *AddInventoriesParams {
	var ()
	return &AddInventoriesParams{

		Context: ctx,
	}
}

// NewAddInventoriesParamsWithHTTPClient creates a new AddInventoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddInventoriesParamsWithHTTPClient(client *http.Client) *AddInventoriesParams {
	var ()
	return &AddInventoriesParams{
		HTTPClient: client,
	}
}

/*AddInventoriesParams contains all the parameters to send to the API endpoint
for the add inventories operation typically these are written to a http.Request
*/
type AddInventoriesParams struct {

	/*Body
	  an array of new inventories

	*/
	Body []*models.Inventory
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add inventories params
func (o *AddInventoriesParams) WithTimeout(timeout time.Duration) *AddInventoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add inventories params
func (o *AddInventoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add inventories params
func (o *AddInventoriesParams) WithContext(ctx context.Context) *AddInventoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add inventories params
func (o *AddInventoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add inventories params
func (o *AddInventoriesParams) WithHTTPClient(client *http.Client) *AddInventoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add inventories params
func (o *AddInventoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add inventories params
func (o *AddInventoriesParams) WithBody(body []*models.Inventory) *AddInventoriesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add inventories params
func (o *AddInventoriesParams) SetBody(body []*models.Inventory) {
	o.Body = body
}

// WithKoronaAccountID adds the koronaAccountID to the add inventories params
func (o *AddInventoriesParams) WithKoronaAccountID(koronaAccountID string) *AddInventoriesParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the add inventories params
func (o *AddInventoriesParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *AddInventoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
