// Code generated by go-swagger; DO NOT EDIT.

package commodity_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewUpdateCommodityGroupParams creates a new UpdateCommodityGroupParams object
// with the default values initialized.
func NewUpdateCommodityGroupParams() *UpdateCommodityGroupParams {
	var ()
	return &UpdateCommodityGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCommodityGroupParamsWithTimeout creates a new UpdateCommodityGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCommodityGroupParamsWithTimeout(timeout time.Duration) *UpdateCommodityGroupParams {
	var ()
	return &UpdateCommodityGroupParams{

		timeout: timeout,
	}
}

// NewUpdateCommodityGroupParamsWithContext creates a new UpdateCommodityGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCommodityGroupParamsWithContext(ctx context.Context) *UpdateCommodityGroupParams {
	var ()
	return &UpdateCommodityGroupParams{

		Context: ctx,
	}
}

// NewUpdateCommodityGroupParamsWithHTTPClient creates a new UpdateCommodityGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCommodityGroupParamsWithHTTPClient(client *http.Client) *UpdateCommodityGroupParams {
	var ()
	return &UpdateCommodityGroupParams{
		HTTPClient: client,
	}
}

/*UpdateCommodityGroupParams contains all the parameters to send to the API endpoint
for the update commodity group operation typically these are written to a http.Request
*/
type UpdateCommodityGroupParams struct {

	/*Body
	  the properties to update of the commodity group

	*/
	Body *models.CommodityGroup
	/*CommodityGroupID
	  id of the related object (important: id should match the uuid-format)

	*/
	CommodityGroupID string
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update commodity group params
func (o *UpdateCommodityGroupParams) WithTimeout(timeout time.Duration) *UpdateCommodityGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update commodity group params
func (o *UpdateCommodityGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update commodity group params
func (o *UpdateCommodityGroupParams) WithContext(ctx context.Context) *UpdateCommodityGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update commodity group params
func (o *UpdateCommodityGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update commodity group params
func (o *UpdateCommodityGroupParams) WithHTTPClient(client *http.Client) *UpdateCommodityGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update commodity group params
func (o *UpdateCommodityGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update commodity group params
func (o *UpdateCommodityGroupParams) WithBody(body *models.CommodityGroup) *UpdateCommodityGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update commodity group params
func (o *UpdateCommodityGroupParams) SetBody(body *models.CommodityGroup) {
	o.Body = body
}

// WithCommodityGroupID adds the commodityGroupID to the update commodity group params
func (o *UpdateCommodityGroupParams) WithCommodityGroupID(commodityGroupID string) *UpdateCommodityGroupParams {
	o.SetCommodityGroupID(commodityGroupID)
	return o
}

// SetCommodityGroupID adds the commodityGroupId to the update commodity group params
func (o *UpdateCommodityGroupParams) SetCommodityGroupID(commodityGroupID string) {
	o.CommodityGroupID = commodityGroupID
}

// WithKoronaAccountID adds the koronaAccountID to the update commodity group params
func (o *UpdateCommodityGroupParams) WithKoronaAccountID(koronaAccountID string) *UpdateCommodityGroupParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the update commodity group params
func (o *UpdateCommodityGroupParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCommodityGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param commodityGroupId
	if err := r.SetPathParam("commodityGroupId", o.CommodityGroupID); err != nil {
		return err
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
