// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductStock product stock
//
// swagger:model ProductStock
type ProductStock struct {

	// amount
	Amount *Amount `json:"amount,omitempty"`

	// average purchase price
	AveragePurchasePrice float64 `json:"averagePurchasePrice,omitempty"`

	// product
	Product *ModelReference `json:"product,omitempty"`

	// revision
	// Read Only: true
	Revision int64 `json:"revision,omitempty"`

	// warehouse
	Warehouse *ModelReference `json:"warehouse,omitempty"`
}

// Validate validates this product stock
func (m *ProductStock) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProduct(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWarehouse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductStock) validateAmount(formats strfmt.Registry) error {

	if swag.IsZero(m.Amount) { // not required
		return nil
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount")
			}
			return err
		}
	}

	return nil
}

func (m *ProductStock) validateProduct(formats strfmt.Registry) error {

	if swag.IsZero(m.Product) { // not required
		return nil
	}

	if m.Product != nil {
		if err := m.Product.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("product")
			}
			return err
		}
	}

	return nil
}

func (m *ProductStock) validateWarehouse(formats strfmt.Registry) error {

	if swag.IsZero(m.Warehouse) { // not required
		return nil
	}

	if m.Warehouse != nil {
		if err := m.Warehouse.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("warehouse")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductStock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductStock) UnmarshalBinary(b []byte) error {
	var res ProductStock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
