// Code generated by go-swagger; DO NOT EDIT.

package external_system_calls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mvnetbiz/go-korona/models"
)

// NewDeleteExternalSystemCallsParams creates a new DeleteExternalSystemCallsParams object
// with the default values initialized.
func NewDeleteExternalSystemCallsParams() *DeleteExternalSystemCallsParams {
	var ()
	return &DeleteExternalSystemCallsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteExternalSystemCallsParamsWithTimeout creates a new DeleteExternalSystemCallsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteExternalSystemCallsParamsWithTimeout(timeout time.Duration) *DeleteExternalSystemCallsParams {
	var ()
	return &DeleteExternalSystemCallsParams{

		timeout: timeout,
	}
}

// NewDeleteExternalSystemCallsParamsWithContext creates a new DeleteExternalSystemCallsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteExternalSystemCallsParamsWithContext(ctx context.Context) *DeleteExternalSystemCallsParams {
	var ()
	return &DeleteExternalSystemCallsParams{

		Context: ctx,
	}
}

// NewDeleteExternalSystemCallsParamsWithHTTPClient creates a new DeleteExternalSystemCallsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteExternalSystemCallsParamsWithHTTPClient(client *http.Client) *DeleteExternalSystemCallsParams {
	var ()
	return &DeleteExternalSystemCallsParams{
		HTTPClient: client,
	}
}

/*DeleteExternalSystemCallsParams contains all the parameters to send to the API endpoint
for the delete external system calls operation typically these are written to a http.Request
*/
type DeleteExternalSystemCallsParams struct {

	/*Body
	  array of existing external system calls (id or number required)

	*/
	Body []*models.ExternalSystemCall
	/*KoronaAccountID
	  account id of the KORONA.cloud account

	*/
	KoronaAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) WithTimeout(timeout time.Duration) *DeleteExternalSystemCallsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) WithContext(ctx context.Context) *DeleteExternalSystemCallsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) WithHTTPClient(client *http.Client) *DeleteExternalSystemCallsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) WithBody(body []*models.ExternalSystemCall) *DeleteExternalSystemCallsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) SetBody(body []*models.ExternalSystemCall) {
	o.Body = body
}

// WithKoronaAccountID adds the koronaAccountID to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) WithKoronaAccountID(koronaAccountID string) *DeleteExternalSystemCallsParams {
	o.SetKoronaAccountID(koronaAccountID)
	return o
}

// SetKoronaAccountID adds the koronaAccountId to the delete external system calls params
func (o *DeleteExternalSystemCallsParams) SetKoronaAccountID(koronaAccountID string) {
	o.KoronaAccountID = koronaAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteExternalSystemCallsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param koronaAccountId
	if err := r.SetPathParam("koronaAccountId", o.KoronaAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
